name: PR Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: test-env
          channels: conda-forge
          channel-priority: strict
          python-version: "3.12"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y pip pytest pytao openpmd-beamphysics
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        env:
          PGPLOT_DEV: /null
        run: |
          pytest -q
